#!/usr/bin/env bash
# Copyright 2019 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
# Startup hook for the sommelier service.  You should not need to modify this
# file as customizations may be placed in ~/.sommelierrc instead.
#
# For documentation, see:
# https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/vm_tools/sommelier/
set -eu
set -o pipefail

: "${CREW_PREFIX:=/usr/local}"

# Set Xft.dpi. Some applications (e.g. Chrome) use this to detect HiDPI.
if command -v xrdb > /dev/null; then
  if [[ -n "${SOMMELIER_DPI:-}" ]]; then
    # set Xft.dpi to SOMMELIER_DPI if set
    DPI="${SOMMELIER_DPI}"
  elif [ -f "${CREW_PREFIX}"/etc/sommelier.dpi ]; then
    # set Xft.dpi with the value in sommelier.dpi if SOMMELIER_DPI not set
    DPI="$(< "${CREW_PREFIX}"/etc/sommelier.dpi)"
  else
    # set Xft.dpi to 96 if sommelier.dpi does not exist
    DPI=96
  fi

  xrdb -merge <<< "Xft.dpi: ${DPI}"

  # Set cursor theme
  if [[ ! "$(xrdb -get Xcursor.theme)" ]]; then
    xrdb -merge <<< 'Xcursor.theme: Adwaita'
  fi
fi

if command -v xsetroot > /dev/null; then
  xsetroot -cursor_name left_ptr
fi

# allow privileged apps to access X display (allow root user)
if command -v xhost > /dev/null; then
  xhost +si:localuser:root
fi

if [ -f ~/.sommelierrc ]; then
  source ~/.sommelierrc
fi

exit 0
